"""Change column types

Revision ID: 3bfe0462c383
Revises: 5004204c3de9
Create Date: 2023-06-23 16:33:21.122309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bfe0462c383'
down_revision = '5004204c3de9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brain_response_data', 'answer',
                    existing_type=sa.String(), nullable=True, new_type=sa.Text(), schema='bot_interaction_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('brain_response_data', 'answer',
                    existing_type=sa.Text(), nullable=True, new_type=sa.String(), schema='bot_interaction_stats')
    # ### end Alembic commands ###
