version: '3'
services:
  app:
    image: ghcr.io/mpodreshetnikov/data-monster-ai/docker-image:latest
    volumes:
      - ./logs:/app/logs
      - ./settings.ini:/app/settings.ini
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_CLEANUP=true
    command: --interval 30
